# .streamlit/secrets.toml
[connections.mydb]
dialect = "postgresql"
host = "vm01.sf.di.univr.it"
port = 5433
database = "mimic"
schema = "mimic_iv_2_2_untouched"
username = "Mattia Danese"
password = "M@tti@!"